# -*- coding: utf-8 -*-
"""graph_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FeO648xgbmbo3xloTLn7EAAkMQCKuV20
"""

import pandas as pd
import numpy as np
import ast
from sklearn.cluster import KMeans
import joblib
import networkx as nx
from tqdm import tqdm

"""data preparing"""

import numpy as np

# تبدیل رشته state به آرایه numpy
def clean_state_format(state_str):
    # حذف نویسه‌های اضافی
    state_str = state_str.strip("[]")  # حذف براکت‌های اضافی از ابتدا و انتها
    # تبدیل رشته به آرایه با فاصله‌ها
    state_list = state_str.split()
    # تبدیل به numpy array
    state_array = np.array(state_list, dtype=float)
    return state_array

def flatten_state(state_str):
    try:
        # تمیز کردن و تبدیل رشته به آرایه
        arr = clean_state_format(state_str)
        return arr
    except Exception as e:
        print(f"❌ Error parsing state: {state_str[:50]}... → {e}")
        return None

# آدرس فایل CSV
file_path = '/content/drive/MyDrive/DialogDQN-Variants/replay_data_movie10000_after30-50.csv'

# خواندن فایل CSV
df = pd.read_csv(file_path)

# 2. پردازش داده‌ها
states = df['state'].apply(flatten_state)

# حذف حالت‌هایی که None برگشت دادن
states = states.dropna()

print(f"✅ تعداد stateهای سالم: {len(states)}")

# بررسی اینکه آیا چیزی برای stack وجود داره؟
if len(states) == 0:
    raise ValueError("⛔ هیچ state معتبری پیدا نشد. ابتدا فایل CSV رو چک کن.")

# تبدیل داده‌ها به آرایه numpy
X = np.stack(states.values)

"""kmeans and graph construction"""

import numpy as np
import pandas as pd
import ast
import joblib
from sklearn.cluster import KMeans
import networkx as nx
from tqdm import tqdm

# 1. خواندن فایل
import numpy as np

# تبدیل رشته state به آرایه numpy
def clean_state_format(state_str):
    # حذف نویسه‌های اضافی
    state_str = state_str.strip("[]")  # حذف براکت‌های اضافی از ابتدا و انتها
    # تبدیل رشته به آرایه با فاصله‌ها
    state_list = state_str.split()
    # تبدیل به numpy array
    state_array = np.array(state_list, dtype=float)
    return state_array

def flatten_state(state_str):
    try:
        # تمیز کردن و تبدیل رشته به آرایه
        arr = clean_state_format(state_str)
        return arr
    except Exception as e:
        print(f"❌ Error parsing state: {state_str[:50]}... → {e}")
        return None

# 2. پردازش داده‌ها
states = df['state'].apply(flatten_state)

# حذف حالت‌هایی که None برگشت دادن
states = states.dropna()

print(f"✅ تعداد stateهای سالم: {len(states)}")

# بررسی اینکه آیا چیزی برای stack وجود داره؟
if len(states) == 0:
    raise ValueError("⛔ هیچ state معتبری پیدا نشد. ابتدا فایل CSV رو چک کن.")

# تبدیل داده‌ها به آرایه numpy
X = np.stack(states.values)


# بررسی طول states و اولین چند مقدار
print(f"تعداد stateهای موجود: {len(states)}")
print("اولین چند مقدار stateها:")
print(states.head())

# تبدیل داده‌ها به آرایه numpy
if len(states) > 0:
    X = np.stack(states.values)
else:
    print("⛔ هیچ state معتبری پیدا نشد.")

# 3. اجرای KMeans یا لود از فایل
k = 40
kmeans_path = "/content/drive/MyDrive/DialogDQN-Variants/kmeans_modelMovie_k40.joblib"

try:
    kmeans = joblib.load(kmeans_path)
    print("✅ مدل KMeans از فایل لود شد.")
except:
    print("⏳ در حال آموزش KMeans...")
    kmeans = KMeans(n_clusters=k, random_state=0)
    kmeans.fit(X)
    joblib.dump(kmeans, kmeans_path)
    print("✅ مدل KMeans ذخیره شد.")

"""# 4. ساخت گراف ترنزیشن بین کلاسترها
G = nx.DiGraph()

print("🔗 در حال ساخت گراف بین کلاسترها...")

for i in tqdm(range(len(df))):
    try:
        s = flatten_state(df.loc[i, 'state'])
        ns = flatten_state(df.loc[i, 'next_state'])

        if s is None or ns is None:
            continue

        s_cluster = kmeans.predict([s])[0]
        ns_cluster = kmeans.predict([ns])[0]

        if G.has_edge(s_cluster, ns_cluster):
            G[s_cluster][ns_cluster]['weight'] += 1
        else:
            G.add_edge(s_cluster, ns_cluster, weight=1)
    except Exception as e:
        print(f"خطا در پردازش داده‌ها: {e}")
        continue

print(f"✅ گراف ساخته شد! {G.number_of_nodes()} نود و {G.number_of_edges()} یال دارد.")
"""
# 4. ساخت گراف ترنزیشن بین کلاسترها با ذخیره بردار ویژگی نودها
G = nx.DiGraph()

print("🔗 در حال ساخت گراف بین کلاسترها و افزودن ویژگی نودها...")

# افزودن نودها همراه با بردار ویژگی (centroid)
for cluster_id in range(k):
    centroid = kmeans.cluster_centers_[cluster_id]
    G.add_node(cluster_id, feature=centroid)

# افزودن یال‌ها بر اساس ترنزیشن بین کلاسترها
for i in tqdm(range(len(df))):
    try:
        s = flatten_state(df.loc[i, 'state'])
        ns = flatten_state(df.loc[i, 'next_state'])

        if s is None or ns is None:
            continue

        s_cluster = kmeans.predict([s])[0]
        ns_cluster = kmeans.predict([ns])[0]

        if G.has_edge(s_cluster, ns_cluster):
            G[s_cluster][ns_cluster]['weight'] += 1
        else:
            G.add_edge(s_cluster, ns_cluster, weight=1)
    except Exception as e:
        print(f"خطا در پردازش داده‌ها: {e}")
        continue

print(f"✅ گراف ساخته شد! {G.number_of_nodes()} نود و {G.number_of_edges()} یال دارد.")

import pickle

with open("/content/drive/MyDrive/DialogDQN-Variants/movie40transition_graph_nodeFeature.pkl", "wb") as f:
    pickle.dump(G, f)

print("✅ گراف با فرمت pickle ذخیره شد.")

nx.write_edgelist(G, "/content/drive/MyDrive/DialogDQN-Variants/movie40transition_graph_nodeFeature.edgelist")
print("✅ گراف به صورت edgelist ذخیره شد.")

import pickle
import networkx as nx

# بارگذاری گراف
with open("/content/drive/MyDrive/DialogDQN-Variants/movie40transition_graph_nodeFeature.pkl", "rb") as f:
    G = pickle.load(f)

# اطلاعات کلی
print("✅ تعداد گره‌ها:", G.number_of_nodes())
print("✅ تعداد یال‌ها:", G.number_of_edges())

# دیدن نمونه‌ای از گره‌ها و ویژگی‌هاشون
print("\n📌 چند نمونه از گره‌ها با ویژگی‌ها:")
for i, (node, data) in enumerate(G.nodes(data=True)):
    print(f"گره {node}: ویژگی‌ها -> {data}")
    if i >= 4:  # فقط ۵ گره اول رو نشون بده
        break

# نوع یال‌ها (آرک‌ها)
print("\n📌 چند نمونه از یال‌ها:")
for i, edge in enumerate(G.edges()):
    print(f"یال {i+1}: {edge}")
    if i >= 4:
        break

import pickle
import networkx as nx

# بارگذاری گراف
with open("/content/drive/MyDrive/DialogDQN-Variants/movie40transition_graph_nodeFeature.pkl", "rb") as f:
    G = pickle.load(f)

# اطلاعات کلی
print("✅ تعداد گره‌ها:", G.number_of_nodes())
print("✅ تعداد یال‌ها:", G.number_of_edges())

# دیدن نمونه‌ای از گره‌ها و ویژگی‌هاشون
print("\n📌 چند نمونه از گره‌ها با ویژگی‌ها:")
for i, (node, data) in enumerate(G.nodes(data=True)):
    print(f"گره {node}: ویژگی‌ها -> {data}")
    if i >= 4:  # فقط ۵ گره اول رو نشون بده
        break

# نوع یال‌ها (آرک‌ها)
print("\n📌 چند نمونه از یال‌ها:")
for i, edge in enumerate(G.edges()):
    print(f"یال {i+1}: {edge}")
    if i >= 4:
        break

import pickle
import networkx as nx
import matplotlib.pyplot as plt

# بارگذاری گراف از فایل
with open("/content/drive/MyDrive/DialogDQN-Variants/movie40transition_graph_nodeFeature.pkl", "rb") as f:
    G = pickle.load(f)

# اطمینان از اینکه نودها integer هستن
G_clean = nx.DiGraph()
for u, v in G.edges():
    G_clean.add_edge(int(u), int(v))

# رسم کل گراف
plt.figure(figsize=(14, 10))
pos = nx.spring_layout(G_clean, seed=42)  # layout برای پخش بهتر نودها
nx.draw(G_clean, pos, with_labels=True, node_color='skyblue', edge_color='gray', node_size=900, font_size=10)
plt.title("Full Transition Graph")
plt.show()

import numpy as np
import pandas as pd

# استخراج ویژگی‌ها
node_features = []
node_ids = []

for node_id in G.nodes():
    feature = G.nodes[node_id]['feature']
    node_ids.append(node_id)
    node_features.append(feature)

# تبدیل به numpy array
features_array = np.vstack(node_features)

# ذخیره به صورت .npy
np.save('/content/drive/MyDrive/DialogDQN-Variants/cluster_node_features.npy', features_array)
print("✅ فایل .npy ذخیره شد.")

# ذخیره به صورت .csv
df_features = pd.DataFrame(features_array, index=node_ids)
df_features.to_csv('/content/drive/MyDrive/DialogDQN-Variants/cluster_node_features.csv')
print("✅ فایل .csv ذخیره شد.")

import matplotlib.pyplot as plt

# رسم گراف با matplotlib
plt.figure(figsize=(12, 12))
nx.draw(G_fixed, with_labels=True, node_size=300, font_size=10, font_weight='bold', node_color='skyblue')
plt.title("movie40 Transition Graph")
plt.show()

"""node2vec"""

!pip install node2vec

!pip install --upgrade numpy
!pip install --upgrade gensim
!pip install node2vec

from node2vec import Node2Vec
import pandas as pd

# گراف باید جهت‌دار باشد یا بی‌جهت؟ بستگی به گراف اصلی‌ات داره
# اگر جهت‌دار است، همین را نگه دار:
import pickle

with open("/content/drive/MyDrive/DialogDQN-Variants/movie40transition_graph.pkl", "rb") as f:
    G_fixed = pickle.load(f)



from node2vec import Node2Vec
import pandas as pd

# اجرای Node2Vec
node2vec = Node2Vec(
    G_fixed,
    dimensions=32,
    walk_length=30,
    num_walks=200,
    workers=2,
    p=1,
    q=2
)

# آموزش مدل
model = node2vec.fit(window=10, min_count=1, batch_words=4)

# استخراج embeddingها
nodes = list(model.wv.index_to_key)
embeddings = [model.wv[node] for node in nodes]

# ذخیره در DataFrame
embedding_df = pd.DataFrame(embeddings, index=nodes)

# ذخیره به CSV
embedding_path = "/content/drive/MyDrive/DialogDQN-Variants/movie40-32n_node2vec_embeddings.csv"
embedding_df.to_csv(embedding_path)

print(f"✅ نود تو‌وِک ذخیره شد: {embedding_path}")

"""manual node2vec"""

import pickle
import networkx as nx
import numpy as np
import random
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
from tqdm import tqdm

# ===================== Load Graph =====================
with open("/content/drive/MyDrive/DialogDQN-Variants/movie40transition_graph.pkl", "rb") as f:
    G_fixed = pickle.load(f)

# Map nodes to integer IDs
node2id = {node: idx for idx, node in enumerate(G_fixed.nodes())}
id2node = {idx: node for node, idx in node2id.items()}
num_nodes = len(node2id)

# ===================== Parameters =====================
embedding_dim = 32
walk_length = 30
num_walks = 10  # per node
context_size = 5
epochs = 5
learning_rate = 0.01
window_size = context_size

# ===================== Random Walk Generator =====================
def generate_random_walk(graph, start_node, walk_length):
    walk = [start_node]
    for _ in range(walk_length - 1):
        neighbors = list(graph.neighbors(walk[-1]))
        if neighbors:
            walk.append(random.choice(neighbors))
        else:
            break
    return walk

all_walks = []
for _ in range(num_walks):
    for node in G_fixed.nodes():
        walk = generate_random_walk(G_fixed, node, walk_length)
        all_walks.append([node2id[n] for n in walk])

# ===================== Generate (center, context) pairs =====================
def generate_skipgram_pairs(walks, window_size):
    pairs = []
    for walk in walks:
        for i in range(len(walk)):
            for j in range(max(0, i - window_size), min(len(walk), i + window_size + 1)):
                if i != j:
                    pairs.append((walk[i], walk[j]))
    return pairs

pairs = generate_skipgram_pairs(all_walks, window_size)

# ===================== PyTorch Model =====================
class Node2Vec(nn.Module):
    def __init__(self, num_nodes, embedding_dim):
        super().__init__()
        self.embeddings = nn.Embedding(num_nodes, embedding_dim)

    def forward(self, center_nodes):
        return self.embeddings(center_nodes)

model = Node2Vec(num_nodes, embedding_dim)
optimizer = optim.Adam(model.parameters(), lr=learning_rate)
loss_fn = nn.CrossEntropyLoss()

# ===================== Training =====================
for epoch in range(epochs):
    total_loss = 0
    random.shuffle(pairs)
    for center, context in tqdm(pairs, desc=f"Epoch {epoch+1}"):
        center_tensor = torch.tensor([center], dtype=torch.long)
        context_tensor = torch.tensor([context], dtype=torch.long)

        logits = model(center_tensor) @ model.embeddings.weight.T  # Dot product
        loss = loss_fn(logits, context_tensor)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1} loss: {total_loss:.4f}")

# ===================== Save Embeddings =====================
embeddings = model.embeddings.weight.detach().numpy()
embedding_df = pd.DataFrame(embeddings, index=[id2node[i] for i in range(num_nodes)])
embedding_path = "/content/drive/MyDrive/DialogDQN-Variants/movie40-32n_node2vec_manual.csv"
embedding_df.to_csv(embedding_path)

print(f"✅ Node2Vec embedding ذخیره شد در: {embedding_path}")

import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import random
from tqdm import tqdm
import pickle

# ===================== Load Graph =====================
with open("/content/drive/MyDrive/DialogDQN-Variants/movie40transition_graph.pkl", "rb") as f:
    G_fixed = pickle.load(f)

# Map nodes to integer IDs
node2id = {node: idx for idx, node in enumerate(G_fixed.nodes())}
id2node = {idx: node for node, idx in node2id.items()}
num_nodes = len(node2id)

# ===================== Parameters =====================
embedding_dim = 32
walk_length = 30
num_walks = 10
context_size = 5
epochs = 3
learning_rate = 0.001
window_size = context_size

# ===================== Load pretrained embeddings =====================
embedding_df = pd.read_csv("/content/drive/MyDrive/DialogDQN-Variants/movie40-32n_node2vec_manual.csv", index_col=0)
pretrained_weights = torch.tensor(embedding_df.values, dtype=torch.float)

# ===================== Define Model =====================
class Node2Vec(nn.Module):
    def __init__(self, num_nodes, embedding_dim, pretrained_weights):
        super().__init__()
        self.embeddings = nn.Embedding(num_nodes, embedding_dim)
        self.embeddings.weight.data = pretrained_weights.clone()

    def forward(self, center_nodes):
        return self.embeddings(center_nodes)

model = Node2Vec(num_nodes, embedding_dim, pretrained_weights)
optimizer = optim.Adam(model.parameters(), lr=learning_rate)
loss_fn = nn.CrossEntropyLoss()

# ===================== Generate Random Walks Again =====================
def generate_random_walk(graph, start_node, walk_length):
    walk = [start_node]
    for _ in range(walk_length - 1):
        neighbors = list(graph.neighbors(walk[-1]))
        if neighbors:
            walk.append(random.choice(neighbors))
        else:
            break
    return walk

all_walks = []
for _ in range(num_walks):
    for node in G_fixed.nodes():
        walk = generate_random_walk(G_fixed, node, walk_length)
        all_walks.append([node2id[n] for n in walk])

# ===================== Generate Skip-Gram Pairs =====================
def generate_skipgram_pairs(walks, window_size):
    pairs = []
    for walk in walks:
        for i in range(len(walk)):
            for j in range(max(0, i - window_size), min(len(walk), i + window_size + 1)):
                if i != j:
                    pairs.append((walk[i], walk[j]))
    return pairs

pairs = generate_skipgram_pairs(all_walks, window_size)

# ===================== Dummy TD Error Dictionary =====================
# ❗تو باید اینو بدی. این فقط یه نمونه است.
td_error_dict = {i: random.random() for i in range(num_nodes)}  # node_id: td_error

# ===================== Fine-tuning =====================
for epoch in range(epochs):
    total_loss = 0
    random.shuffle(pairs)
    for center, context in tqdm(pairs, desc=f"Fine-Tune Epoch {epoch+1}"):
        center_tensor = torch.tensor([center], dtype=torch.long)
        context_tensor = torch.tensor([context], dtype=torch.long)

        logits = model(center_tensor) @ model.embeddings.weight.T
        loss_n2v = loss_fn(logits, context_tensor)

        # TD-error loss
        td_error_loss = torch.tensor([td_error_dict[center]], dtype=torch.float).mean()

        final_loss = loss_n2v + 0.5 * td_error_loss

        optimizer.zero_grad()
        final_loss.backward()
        optimizer.step()

        total_loss += final_loss.item()

    print(f"Epoch {epoch+1} Fine-Tune Loss: {total_loss:.4f}")

# ===================== Save New Embeddings =====================
new_embeddings = model.embeddings.weight.detach().numpy()
new_embedding_df = pd.DataFrame(new_embeddings, index=[id2node[i] for i in range(num_nodes)])
embedding_path = "/content/drive/MyDrive/DialogDQN-Variants/movie40-32n_node2vec_finetuned_manual.csv"
new_embedding_df.to_csv(embedding_path)

print(f"✅ مدل فاین‌تیون‌شده ذخیره شد در: {embedding_path}")

import pandas as pd
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt

# خواندن embeddingها
embedding_path = "/content/drive/MyDrive/DialogDQN-Variants/movie40-32n_node2vec_embeddings.csv"
embedding_df = pd.read_csv(embedding_path, index_col=0)

# کاهش ابعاد با t-SNE
tsne = TSNE(n_components=2, random_state=42, perplexity=10)
embedding_2d = tsne.fit_transform(embedding_df.values)

# رسم
plt.figure(figsize=(10, 8))
plt.scatter(embedding_2d[:, 0], embedding_2d[:, 1], s=30, alpha=0.7)

# نام‌گذاری نودها روی گراف
for i, node_id in enumerate(embedding_df.index):
    plt.text(embedding_2d[i, 0], embedding_2d[i, 1], str(node_id), fontsize=8, alpha=0.6)

plt.title("Node2Vec Embeddings (2D t-SNE Visualization)")
plt.xlabel("t-SNE Dim 1")
plt.ylabel("t-SNE Dim 2")
plt.grid(True)
plt.tight_layout()
plt.show()

!pip install torch-geometric
!pip install torch

"""kmeans and grapg preparing for graphsage"""

import numpy as np
import joblib
from sklearn.cluster import KMeans
import networkx as nx
from tqdm import tqdm

# 1. خواندن داده‌ها و تبدیل به numpy array
def clean_state_format(state_str):
    state_str = state_str.strip("[]")
    state_list = state_str.split()
    state_array = np.array(state_list, dtype=float)
    return state_array

def flatten_state(state_str):
    try:
        arr = clean_state_format(state_str)
        return arr
    except Exception as e:
        print(f"❌ Error parsing state: {state_str[:50]}... → {e}")
        return None

# داده‌ها
states = df['state'].apply(flatten_state)
states = states.dropna()

# تبدیل داده‌ها به آرایه numpy
X = np.stack(states.values)

# 2. اجرای KMeans یا لود از فایل
k = 40
kmeans_path = "/content/drive/MyDrive/DialogDQN-Variants/kmeans_modelMovie_k40.joblib"

try:
    kmeans = joblib.load(kmeans_path)
    print("✅ مدل KMeans از فایل لود شد.")
except:
    print("⏳ در حال آموزش KMeans...")
    kmeans = KMeans(n_clusters=k, random_state=0)
    kmeans.fit(X)
    joblib.dump(kmeans, kmeans_path)
    print("✅ مدل KMeans ذخیره شد.")

# 3. استخراج ویژگی نودها (یعنی مراکز خوشه‌ها)
cluster_centers = kmeans.cluster_centers_

# 4. ساخت گراف ترنزیشن بین کلاسترها
G = nx.DiGraph()

print("🔗 در حال ساخت گراف بین کلاسترها...")

for i in tqdm(range(len(df))):
    try:
        s = flatten_state(df.loc[i, 'state'])
        ns = flatten_state(df.loc[i, 'next_state'])

        if s is None or ns is None:
            continue

        s_cluster = kmeans.predict([s])[0]
        ns_cluster = kmeans.predict([ns])[0]

        if G.has_edge(s_cluster, ns_cluster):
            G[s_cluster][ns_cluster]['weight'] += 1
        else:
            G.add_edge(s_cluster, ns_cluster, weight=1)
    except Exception as e:
        print(f"خطا در پردازش داده‌ها: {e}")
        continue

print(f"✅ گراف ساخته شد! {G.number_of_nodes()} نود و {G.number_of_edges()} یال دارد.")

# 5. ذخیره گراف (برای استفاده بعدی)
graph_path = "/content/drive/MyDrive/DialogDQN-Variants/movie40transition|_feature_graph.pkl"
joblib.dump(G, graph_path)

print(f"✅ گراف ذخیره شد: {graph_path}")

# 6. حالا بردار ویژگی نودها را به صورت CSV ذخیره می‌کنیم
import pandas as pd

# ذخیره مرکز خوشه‌ها به عنوان ویژگی نودها
embedding_df = pd.DataFrame(cluster_centers)
embedding_df.to_csv("/content/drive/MyDrive/DialogDQN-Variants/movie40_node_embeddings_feature.csv", index=False)

print("✅ ویژگی‌های نودها ذخیره شدند.")

import pickle
import networkx as nx
import numpy as np


# بارگذاری گراف
with open("/content/drive/MyDrive/DialogDQN-Variants/movie40transition_graph_nodeFeature.pkl", "rb") as f:
    G = pickle.load(f)
has_feature = 0
no_feature = 0
for node, data in G.nodes(data=True):
    if 'feature' in data and isinstance(data['feature'], (list, tuple, np.ndarray)):
        has_feature += 1
    else:
        no_feature += 1

print("✅ تعداد گره‌هایی که ویژگی دارن:", has_feature)
print("⚠️ تعداد گره‌هایی که ویژگی ندارن:", no_feature)

"""simple graphsage"""

import pickle
import torch
import torch.nn.functional as F
import torch.nn as nn
from torch_geometric.data import Data
from torch_geometric.nn import SAGEConv
from torch_geometric.utils import from_networkx, train_test_split_edges
import networkx as nx
import numpy as np

# 1. Load graph
with open("/content/drive/MyDrive/DialogDQN-Variants/movie40transition_graph_nodeFeature.pkl", "rb") as f:
    G_nx = pickle.load(f)

# 2. Check all nodes have 'feat' and prepare feature matrix
node_feats = []
node_ids = []

for node in G_nx.nodes:
    feat = G_nx.nodes[node].get("feat", None)
    if feat is None:
        raise ValueError(f"Node {node} has no feature!")
    node_feats.append(feat)
    node_ids.append(node)

x_tensor = torch.tensor(np.array(node_feats), dtype=torch.float32)

# 3. Convert to PyG Data object
data = from_networkx(G_nx)
data.x = x_tensor
data = train_test_split_edges(data)  # removes edge_index from data

# 4. Define GraphSAGE model
class GraphSAGE(nn.Module):
    def __init__(self, in_channels, hidden_channels):
        super(GraphSAGE, self).__init__()
        self.conv1 = SAGEConv(in_channels, hidden_channels)
        self.conv2 = SAGEConv(hidden_channels, hidden_channels)

    def encode(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = self.conv2(x, edge_index)
        return x

    def decode(self, z, edge_index):
        return (z[edge_index[0]] * z[edge_index[1]]).sum(dim=1)

    def decode_all(self, z):
        return torch.matmul(z, z.t())

# 5. Training loop
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = GraphSAGE(data.num_node_features, hidden_channels=64).to(device)
x, train_pos_edge_index = data.x.to(device), data.train_pos_edge_index.to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

def get_link_labels(pos_edge_index, neg_edge_index):
    pos_label = torch.ones(pos_edge_index.size(1))
    neg_label = torch.zeros(neg_edge_index.size(1))
    return torch.cat([pos_label, neg_label]).to(device)

for epoch in range(1, 201):
    model.train()
    optimizer.zero_grad()
    z = model.encode(x, train_pos_edge_index)

    pos_edge = data.train_pos_edge_index
    neg_edge = data.train_neg_edge_index
    edge_index = torch.cat([pos_edge, neg_edge], dim=-1)

    pred = model.decode(z, edge_index)
    labels = get_link_labels(pos_edge, neg_edge)
    loss = F.binary_cross_entropy_with_logits(pred, labels)
    loss.backward()
    optimizer.step()

    if epoch % 20 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

# 6. Save model & embeddings
torch.save(model.state_dict(), "/content/drive/MyDrive/DialogDQN-Variants/graphsage_model.pth")
torch.save(z.detach().cpu(), "/content/drive/MyDrive/DialogDQN-Variants/graphsage_node_embeddings.pt")

!pip install torch-geometric
!pip install torch

import stellargraph as sg
import tensorflow as tf
import pickle
import pandas as pd
import torch
import torch.nn.functional as F
import torch.nn as nn
from torch_geometric.data import Data
from torch_geometric.nn import SAGEConv
from torch_geometric.utils import from_networkx, train_test_split_edges
import networkx as nx
import numpy as np

with open("/content/drive/MyDrive/DialogDQN-Variants/movie40transition_graph_nodeFeature.pkl", "rb") as f:
    G = pickle.load(f)

# 1. Prepare node data:
node_features = {node: data.get('feature', {}) for node, data in G.nodes(data=True)}
node_features_df = pd.DataFrame.from_dict(node_features, orient='index')

# 2. Prepare edge data:
edges_df = pd.DataFrame(list(G.edges), columns=["source", "target"])  # Convert to DataFrame

# 3. Create StellarGraph object:
graph = sg.StellarGraph(nodes=node_features_df, edges=edges_df)

print(graph.info())

"""graphsage for k=3000"""

import pickle
import torch
import torch.nn.functional as F
import torch.nn as nn
from torch_geometric.data import Data
from torch_geometric.nn import SAGEConv
from torch_geometric.utils import from_networkx
import networkx as nx
import numpy as np

# 1. Load graph
with open("/content/drive/MyDrive/DialogDQN-Variants/movie40transition_graph_nodeFeature.pkl", "rb") as f:
    G_nx = pickle.load(f)

# 2. Check all nodes have 'feat' and prepare feature matrix
node_feats = []
node_ids = []

for node in G_nx.nodes:
    feat = G_nx.nodes[node].get("feature", None)
    if feat is None:
        raise ValueError(f"Node {node} has no feature!")
    node_feats.append(feat)
    node_ids.append(node)

x_tensor = torch.tensor(np.array(node_feats), dtype=torch.float32)

# 3. Convert to PyG Data object
data = from_networkx(G_nx)
data.x = x_tensor
# No edge splitting for self-supervised learning
# data = train_test_split_edges(data)

# 4. Define GraphSAGE model
class GraphSAGE(nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels):
        super(GraphSAGE, self).__init__()
        self.conv1 = SAGEConv(in_channels, hidden_channels)
        self.conv2 = SAGEConv(hidden_channels, out_channels)
        self.dropout = nn.Dropout(0.2)
        self.bn3 = nn.BatchNorm1d(out_channels) # Batch normalization


    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = F.leaky_relu(x)
        x = self.conv2(x, edge_index)
        return x


# 5. Training loop
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# Set the desired output embedding size here:
embedding_size = 32
model = GraphSAGE(data.num_node_features, hidden_channels=300, out_channels=embedding_size).to(device)
#model = GraphSAGE(data.num_node_features, hidden_channels=300).to(device)
x, edge_index = data.x.to(device), data.edge_index.to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

for epoch in range(1, 601):
    model.train()
    optimizer.zero_grad()
    z = model(x, edge_index)  # Get node embeddings

    # Adjacency matrix reconstruction
    adj_recon = torch.sigmoid(torch.matmul(z, z.t()))

    # Calculate loss (e.g., binary cross-entropy)
    adj_target = torch.zeros(data.num_nodes, data.num_nodes).to(device)
    adj_target[edge_index[0], edge_index[1]] = 1  # Create target adjacency matrix
    loss = F.binary_cross_entropy(adj_recon, adj_target)

    loss.backward()
    optimizer.step()

    if epoch % 20 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

# 6. Save model & embeddings
torch.save(model.state_dict(), "/content/drive/MyDrive/DialogDQN-Variants/movie40graphsage-n32_model_adj_recon.pth")
torch.save(z.detach().cpu(), "/content/drive/MyDrive/DialogDQN-Variants/movie40graphsage-n32_node_embeddings_adj_recon.pt")

import pickle
import torch
import numpy as np
import pandas as pd
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt

# 1. Load the saved embeddings
embedding_path = "/content/drive/MyDrive/DialogDQN-Variants/movie40graphsage_node_embeddings_adj_recon.pt"
embeddings = torch.load(embedding_path).numpy()

# 2. Apply t-SNE to reduce the dimensionality to 2
tsne = TSNE(n_components=2, random_state=42, perplexity=10) # Adjust perplexity if needed
embeddings_2d = tsne.fit_transform(embeddings)

# 3. Create a DataFrame for plotting (optional but helpful for labels)
node_ids = range(embeddings.shape[0])  # Assuming node IDs are 0 to num_nodes - 1
embedding_df = pd.DataFrame(embeddings_2d, index=node_ids, columns=['dim_1', 'dim_2'])

# 4. Plot the embeddings
plt.figure(figsize=(10, 8))
plt.scatter(embedding_df['dim_1'], embedding_df['dim_2'], s=30, alpha=0.7)
plt.title("t-SNE Visualization of GraphSAGE Node Embeddings")
plt.xlabel("t-SNE Dimension 1")
plt.ylabel("t-SNE Dimension 2")

# (Optional) Add labels to the points
for i, node_id in enumerate(embedding_df.index):
    plt.text(embedding_df.loc[node_id, 'dim_1'], embedding_df.loc[node_id, 'dim_2'], str(node_id), fontsize=8, alpha=0.6)

plt.grid(True)
plt.tight_layout()
plt.show()

"""run project"""

#simple dqn, nv -is, n=32, k=40

!bash script/movie.sh







